flags = {
    "AC_Ascension_Island": "🇦🇨",
    "AD_Andorra": "🇦🇩",
    "AE_United Arab Emirates": "🇦🇪",
    "AF_Afghanistan": "🇦🇫",
    "AG_Antigua Barbuda": "🇦🇬",
    "AI_Anguilla": "🇦🇮",
    "AL_Albania": "🇦🇱",
    "AM_Armenia": "🇦🇲",
    "AO_Angola": "🇦🇴",
    "AQ_Antarctica": "🇦🇶",
    "AR_Argentina": "🇦🇷",
    "AS_American Samoa": "🇦🇸",
    "AT_Austria": "🇦🇹",
    "AU_Australia": "🇦🇺",
    "AW_Aruba": "🇦🇼",
    "AX_Aland Islands": "🇦🇽",
    "AZ_Azerbaijan": "🇦🇿",
    "BA_Bosnia Herzegovina": "🇧🇦",
    "BB_Barbados": "🇧🇧",
    "BD_Bangladesh": "🇧🇩",
    "BE_Belgium": "🇧🇪",
    "BF_Burkina Faso": "🇧🇫",
    "BG_Bulgaria": "🇧🇬",
    "BH_Bahrain": "🇧🇭",
    "BI_Burundi": "🇧🇮",
    "BJ_Benin": "🇧🇯",
    "BL_St_Barthelemy": "🇧🇱",
    "BM_Bermuda": "🇧🇲",
    "BN_Brunei": "🇧🇳",
    "BO_Bolivia": "🇧🇴",
    "BQ_Caribbean Netherlands": "🇧🇶",
    "BR_Brazil": "🇧🇷",
    "BS_Bahamas": "🇧🇸",
    "BT_Bhutan": "🇧🇹",
    "BV_Bouvet Island": "🇧🇻",
    "BW_Botswana": "🇧🇼",
    "BY_Belarus": "🇧🇾",
    "BZ_Belize": "🇧🇿",
    "CA_Canada": "🇨🇦",
    "CC_Cocos Islands": "🇨🇨",
    "CD_Congo Kinshasa": "🇨🇩",
    "CF_Central African Republic": "🇨🇫",
    "CG_Congo Brazzaville": "🇨🇬",
    "CH_Switzerland": "🇨🇭",
    "CI_Cote d Ivoire": "🇨🇮",
    "CK_Cook Islands": "🇨🇰",
    "CL_Chile": "🇨🇱",
    "CM_Cameroon": "🇨🇲",
    "CN_China": "🇨🇳",
    "CO_Colombia": "🇨🇴",
    "CP_Clipperton Island": "🇨🇵",
    "CR_Costa Rica": "🇨🇷",
    "CU_Cuba": "🇨🇺",
    "CV_Cape Verde": "🇨🇻",
    "CW_Curacao": "🇨🇼",
    "CX_Christmas Island": "🇨🇽",
    "CY_Cyprus": "🇨🇾",
    "CZ_Czech_Republic": "🇨🇿",
    "DE_Germany": "🇩🇪",
    "DG_Diego Garcia": "🇩🇬",
    "DJ_Djibouti": "🇩🇯",
    "DK_Denmark": "🇩🇰",
    "DM_Dominica": "🇩🇲",
    "DO_Dominican Republic": "🇩🇴",
    "DZ_Algeria": "🇩🇿",
    "EA_Ceuta Melilla": "🇪🇦",
    "EC_Ecuador": "🇪🇨",
    "EE_Estonia": "🇪🇪",
    "EG_Egypt": "🇪🇬",
    "EH_Western Sahara": "🇪🇭",
    "ER_Eritrea": "🇪🇷",
    "ES_Spain": "🇪🇸",
    "ET_Ethiopia": "🇪🇹",
    "EU_European Union": "🇪🇺",
    "FI_Finland": "🇫🇮",
    "FJ_Fiji": "🇫🇯",
    "FK_Falkland Islands": "🇫🇰",
    "FM_Micronesia": "🇫🇲",
    "FO_Faroe Islands": "🇫🇴",
    "FR_France": "🇫🇷",
    "GA_Gabon": "🇬🇦",
    "GB_United Kingdom": "🇬🇧",
    "GD_Grenada": "🇬🇩",
    "GE_Georgia": "🇬🇪",
    "GF_French Guiana": "🇬🇫",
    "GG_Guernsey": "🇬🇬",
    "GH_Ghana": "🇬🇭",
    "GI_Gibraltar": "🇬🇮",
    "GL_Greenland": "🇬🇱",
    "GM_Gambia": "🇬🇲",
    "GN_Guinea": "🇬🇳",
    "GP_Guadeloupe": "🇬🇵",
    "GQ_Equatorial Guinea": "🇬🇶",
    "GR_Greece": "🇬🇷",
    "GS_South Georgia South Sandwich Islands": "🇬🇸",
    "GT_Guatemala": "🇬🇹",
    "GU_Guam": "🇬🇺",
    "GW_Guinea-Bissau": "🇬🇼",
    "GY_Guyana": "🇬🇾",
    "HK_Hong Kong": "🇭🇰",
    "HM_Heard McDonald Islands": "🇭🇲",
    "HN_Honduras": "🇭🇳",
    "HR_Croatia": "🇭🇷",
    "HT_Haiti": "🇭🇹",
    "HU_Hungary": "🇭🇺",
    "IC_Canary Islands": "🇮🇨",
    "ID_Indonesia": "🇮🇩",
    "IE_Ireland": "🇮🇪",
    "IL_Israel": "🇮🇱",
    "IM_Isle of Man": "🇮🇲",
    "IN_India": "🇮🇳",
    "IO_British Indian Ocean Territory": "🇮🇴",
    "IQ_Iraq": "🇮🇶",
    "IR_Iran": "🇮🇷",
    "IS_Iceland": "🇮🇸",
    "IT_Italy": "🇮🇹",
    "JE_Jersey": "🇯🇪",
    "JM_Jamaica": "🇯🇲",
    "JO_Jordan": "🇯🇴",
    "JP_Japan": "🇯🇵",
    "KE_Kenya": "🇰🇪",
    "KG_Kyrgyzstan": "🇰🇬",
    "KH_Cambodia": "🇰🇭",
    "KI_Kiribati": "🇰🇮",
    "KM_Comoros": "🇰🇲",
    "KN_St Kitts Nevis": "🇰🇳",
    "KP_North Korea": "🇰🇵",
    "KR_South Korea": "🇰🇷",
    "KW_Kuwait": "🇰🇼",
    "KY_Cayman Islands": "🇰🇾",
    "KZ_Kazakhstan": "🇰🇿",
    "LA_Laos": "🇱🇦",
    "LB_Lebanon": "🇱🇧",
    "LC_St Lucia": "🇱🇨",
    "LI_Liechtenstein": "🇱🇮",
    "LK_Sri Lanka": "🇱🇰",
    "LR_Liberia": "🇱🇷",
    "LS_Lesotho": "🇱🇸",
    "LT_Lithuania": "🇱🇹",
    "LU_Luxembourg": "🇱🇺",
    "LV_Latvia": "🇱🇻",
    "LY_Libya": "🇱🇾",
    "MA_Morocco": "🇲🇦",
    "MC_Monaco": "🇲🇨",
    "MD_Moldova": "🇲🇩",
    "ME_Montenegro": "🇲🇪",
    "MF_St Martin": "🇲🇫",
    "MG_Madagascar": "🇲🇬",
    "MH_Marshall Islands": "🇲🇭",
    "MK_North Macedonia": "🇲🇰",
    "ML_Mali": "🇲🇱",
    "MM_Myanmar (Burma)": "🇲🇲",
    "MN_Mongolia": "🇲🇳",
    "MO_Macao SAR China": "🇲🇴",
    "MP_Northern Mariana Islands": "🇲🇵",
    "MQ_Martinique": "🇲🇶",
    "MR_Mauritania": "🇲🇷",
    "MS_Montserrat": "🇲🇸",
    "MT_Malta": "🇲🇹",
    "MU_Mauritius": "🇲🇺",
    "MV_Maldives": "🇲🇻",
    "MW_Malawi": "🇲🇼",
    "MX_Mexico": "🇲🇽",
    "MY_Malaysia": "🇲🇾",
    "MZ_Mozambique": "🇲🇿",
    "NA_Namibia": "🇳🇦",
    "NC_New Caledonia": "🇳🇨",
    "NE_Niger": "🇳🇪",
    "NF_Norfolk Island": "🇳🇫",
    "NG_Nigeria": "🇳🇬",
    "NI_Nicaragua": "🇳🇮",
    "NL_Netherlands": "🇳🇱",
    "NO_Norway": "🇳🇴",
    "NP_Nepal": "🇳🇵",
    "NR_Nauru": "🇳🇷",
    "NU_Niue": "🇳🇺",
    "NZ_New Zealand": "🇳🇿",
    "OM_Oman": "🇴🇲",
    "PA_Panama": "🇵🇦",
    "PE_Peru": "🇵🇪",
    "PF_French Polynesia": "🇵🇫",
    "PG_Papua New Guinea": "🇵🇬",
    "PH_Philippines": "🇵🇭",
    "PK_Pakistan": "🇵🇰",
    "PL_Poland": "🇵🇱",
    "PM_St Pierre Miquelon": "🇵🇲",
    "PN_Pitcairn Islands": "🇵🇳",
    "PR_Puerto Rico": "🇵🇷",
    "PS_Palestinian Territories": "🇵🇸",
    "PT_Portugal": "🇵🇹",
    "PW_Palau": "🇵🇼",
    "PY_Paraguay": "🇵🇾",
    "QA_Qatar": "🇶🇦",
    "RE_Reunion": "🇷🇪",
    "RO_Romania": "🇷🇴",
    "RS_Serbia": "🇷🇸",
    "RU_Russia": "🇷🇺",
    "RW_Rwanda": "🇷🇼",
    "SA_Saudi Arabia": "🇸🇦",
    "SB_Solomon Islands": "🇸🇧",
    "SC_Seychelles": "🇸🇨",
    "SD_Sudan": "🇸🇩",
    "SE_Sweden": "🇸🇪",
    "SG_Singapore": "🇸🇬",
    "SH_St Helena": "🇸🇭",
    "SI_Slovenia": "🇸🇮",
    "SJ_Svalbard Jan Mayen": "🇸🇯",
    "SK_Slovakia": "🇸🇰",
    "SL_Sierra Leone": "🇸🇱",
    "SM_San Marino": "🇸🇲",
    "SN_Senegal": "🇸🇳",
    "SO_Somalia": "🇸🇴",
    "SR_Suriname": "🇸🇷",
    "SS_South Sudan": "🇸🇸",
    "ST_Sao Tome Principe": "🇸🇹",
    "SV_El Salvador": "🇸🇻",
    "SX_Sint Maarten": "🇸🇽",
    "SY_Syria": "🇸🇾",
    "SZ_Eswatini": "🇸🇿",
    "TA_Tristan da Cunha": "🇹🇦",
    "TC_Turks Caicos Islands": "🇹🇨",
    "TD_Chad": "🇹🇩",
    "TF_French Southern Territories": "🇹🇫",
    "TG_Togo": "🇹🇬",
    "TH_Thailand": "🇹🇭",
    "TJ_Tajikistan": "🇹🇯",
    "TK_Tokelau": "🇹🇰",
    "TL_Timor-Leste": "🇹🇱",
    "TM_Turkmenistan": "🇹🇲",
    "TN_Tunisia": "🇹🇳",
    "TO_Tonga": "🇹🇴",
    "TR_Turkiye": "🇹🇷",
    "TT_Trinidad Tobago": "🇹🇹",
    "TV_Tuvalu": "🇹🇻",
    "TW_Taiwan": "🇹🇼",
    "TZ_Tanzania": "🇹🇿",
    "UA_Ukraine": "🇺🇦",
    "UG_Uganda": "🇺🇬",
    "UM_US Outlying Islands": "🇺🇲",
    "UN_United Nations": "🇺🇳",
    "US_United States": "🇺🇸",
    "UY_Uruguay": "🇺🇾",
    "UZ_Uzbekistan": "🇺🇿",
    "VA_Vatican City": "🇻🇦",
    "VC_St Vincent Grenadines": "🇻🇨",
    "VE_Venezuela": "🇻🇪",
    "VG_British Virgin Islands": "🇻🇬",
    "VI_US Virgin Islands": "🇻🇮",
    "VN_Vietnam": "🇻🇳",
    "VU_Vanuatu": "🇻🇺",
    "WF_Wallis Futuna": "🇼🇫",
    "WS_Samoa": "🇼🇸",
    "XK_Kosovo": "🇽🇰",
    "YE_Yemen": "🇾🇪",
    "YT_Mayotte": "🇾🇹",
    "ZA_South Africa": "🇿🇦",
    "ZM_Zambia": "🇿🇲",
    "ZW_Zimbabwe": "🇿🇼"
}
